### ISSUE TITLE
Custom background feature request

### ISSUE THREAD

**Issue by andry1234-cpu** [Jip-Hop/mappertje#1]
Hi Jip-Hop,
do you think that a custom background adding function would be possible to implement?

Thank you, very nice job

**Comment by Jip-Hop** [comment]
I totally missed this request!

Sorry, I have no plans to do this. But since mappertje runs in a browser, it's easy to do this yourself (albeit you'd have to do it again every time).

In Chrome, right click in the page and select `Inspect`. In the DevTools window that opens, select the `<html>` element (at the top, you may need to scroll up). Then you can change the background color (or specify an image, but you'd have to know some CSS to make it look right I suppose).

<img width="1162" alt="Screenshot 2023-01-06 at 11 21 58" src="https://user-images.githubusercontent.com/2871973/210986086-fad67847-444d-4325-8a63-5d4bdb7592d6.png">

If you don't want to change this every time, you can host your own (modified) version of mappertje [as I explained here](https://github.com/Jip-Hop/mappertje/issues/3#issuecomment-1373437736).
