### ISSUE TITLE
Frame drops while sharing window screen

### ISSUE THREAD

**Issue by dortamiguel** [Jip-Hop/mappertje#3]
Hi, thank you very much for this plugin, the UX works really well and I couldn't found another simple to use software like this.

I'm using it to fix some warping to watch a movie with a projector and it works fine for this purpose. Only thing I see is that the framerate of the video is not smooth and quality drops.

You think is possible to improve the quality of the stream to get same 24fps with a movie from VLC?

**Comment by dortamiguel** [comment]
It seems to be a limitation of both firefox and chrome. I think electronjs doesn't has this problem, could be possible to package this app using that framework?

**Comment by Jip-Hop** [comment]
Glad to hear you're enjoying the UX. 🙂

I just tried to map a 1080p movie trailer playing in VLC on one screen to a second 4k screen. I was able to get good performance. Are you using a Mac or Windows PC?

These observations are from Chrome on a Mac:

- Capturing a Window (instead of the whole screen) is noticeably laggier. For best performance, connect your projector as a second screen (don't duplicate the main screen). You can then put VLC in full-screen on your regular monitor, and put mappertje on the projector.
- If you must capture a Window, make it as small as possible. The lag goes away and I found the quality to still be good.

I have no plans to package mappertje with electron (and I don't think doing this will improve the performance). Electron doesn't include the menu which allows you to choose the source to capture (window, screen, chrome tab), so it takes some effort to make it work in electron.

If you must have 24p (for performance reasons) you may download mappertje as a zip file and [change this line](https://github.com/Jip-Hop/mappertje/blob/master/src/modules/index.js#L177) to make it look like this:

```javascript
      .getDisplayMedia({
        video: {frameRate: 24}
      })
```

If you then serve the downloaded `/src` folder with a local server you will be capturing at 24fps. For example with python: `python3 -m http.server 8080 --bind 127.0.0.1 --directory /Users/you/Downloads/mappertje-master/src`. Then open http://127.0.0.1:8080/ in Chrome.

I hope this works out for you!

**Comment by dortamiguel** [comment]
I see! Thanks, another trick I found is creating a virtual camera with obs, it seems to be a lot more performant without any framedrops

**Comment by Jip-Hop** [comment]
Nice!
